name: CI Build for Docker Action

on:
  push:
    branches: main
    paths: [hello-world-docker-actions/**]
  workflow_dispatch:

jobs:
  test-action:
    name: Test Action
    runs-on: ubuntu-lates
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run my own container action
        id: hello-action
        uses: ./hellow-world-docker-action
        with:
           who-to-greet: '@bbrow14n-1'

      - name: Ooutput time set in the container
        run: echo "The time was $PP steps.hello-action.outputs.time }} when the action said hellow"
